# netlify.toml
[build]
  base = "propulsor-crm"            # pasta onde está o projeto React/Vite
  publish = "propulsor-crm/dist"    # saída padrão do Vite
  command = "npm install && npm run build"

[dev]
  command = "npm run dev"

[functions]
  directory = "netlify/functions"
