# netlify.toml

[build]
  command = "bash download_sqlite_bancos.sh && npm run build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"

[dev]
  command = "npm run dev"

[functions]
  directory = "netlify/functions"
