# netlify.toml


[build]
command = "bash baixar_bancos_propulsor.sh && npm run build"
publish = "build"

[build.environment]
PYTHON_VERSION = "3.11"
NODE_VERSION = "20"

[build.environment]
  NODE_ENV = "production"

[dev]
  command = "npm run dev"

[functions]
  directory = "netlify/functions"
