CREATE TABLE IF NOT EXISTS db_categoria (
  "#Categoria" TEXT,
  "Categoria" TEXT,
  "ID" TEXT
);

INSERT INTO db_categoria ("#Categoria", "Categoria", "ID") VALUES ('Cível', 'Administrativo', '1');
INSERT INTO db_categoria ("#Categoria", "Categoria", "ID") VALUES ('Cível', 'Cível', '2');
INSERT INTO db_categoria ("#Categoria", "Categoria", "ID") VALUES ('Trabalhista', 'Trabalhista', '3');
INSERT INTO db_categoria ("#Categoria", "Categoria", "ID") VALUES ('Trabalhista', 'Administrativo Trabalhista', '4');
INSERT INTO db_categoria ("#Categoria", "Categoria", "ID") VALUES ('Cível', 'Criminal', '5');
INSERT INTO db_categoria ("#Categoria", "Categoria", "ID") VALUES ('Tributário', 'Tributário', '6');
INSERT INTO db_categoria ("#Categoria", "Categoria", "ID") VALUES ('Cível', 'Família', '7');
INSERT INTO db_categoria ("#Categoria", "Categoria", "ID") VALUES ('Tributário', 'Administrativo Fiscal', '8');
INSERT INTO db_categoria ("#Categoria", "Categoria", "ID") VALUES ('Cível', 'Ambiental', '9');
INSERT INTO db_categoria ("#Categoria", "Categoria", "ID") VALUES ('Cível', 'Previdenciário', '10');

CREATE TABLE IF NOT EXISTS db_clientes (
  "#Clientes" TEXT,
  "CPF_CNPJ" TEXT,
  "CPF_CNPJ_Conv" TEXT,
  "Clientes" TEXT,
  "Clientes_Maiusc" TEXT,
  "Índice" TEXT
);

INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('ABR - Associação Brasileira do Segmento de Reforma de Pneus', 'None', 'None', 'ABR - Associação Brasileira do Segmento de Reforma de Pneus', 'ABR - ASSOCIAÇÃO BRASILEIRA DO SEGMENTO DE REFORMA DE PNEUS', '1');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Alpar Participações Ltda.', '12.697.012/0001-04', '12697012000104', 'Alpar Participações Ltda.', 'ALPAR PARTICIPAÇÕES LTDA.', '2');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Angelita Borges Paludo', 'None', 'None', 'Angelita Borges Paludo', 'ANGELITA BORGES PALUDO', '3');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Angilucca Participações S.A.', '09.204.861/0001-66', '9204861000166.0', 'Angilucca Participações S.A.', 'ANGILUCCA PARTICIPAÇÕES S.A.', '4');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('APFPAR Participações S.A.', '16.749.597/0001-01', '16749597000101.0', 'Ardan Participações S.A.', 'APFPAR PARTICIPAÇÕES S.A.', '5');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Arlindo Paludo', '026.462.180-87', '2646218087.0', 'Arlindo Paludo', 'ARLINDO PALUDO', '6');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('APFPAR Participações S.A.', '00.279.226/0001-73', '279226000173.0', 'Arpal Participações S.A.', 'APFPAR PARTICIPAÇÕES S.A.', '7');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Associação Esportiva, Recreativa, Cultural e Assistencial dos Funcionários do Grupo Vipal - AFUVI', '89.986.186/0001-03', '89986186000103.0', 'Associação Esportiva, Recreativa, Cultural e Assistencial dos Funcionários do Grupo Vipal - AFUVI', 'ASSOCIAÇÃO ESPORTIVA, RECREATIVA, CULTURAL E ASSISTENCIAL DOS FUNCIONÁRIOS DO GRUPO VIPAL - AFUVI', '8');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Asuncor Negócios Imobiliários Ltda.', '11.401.157/0001-45', '11401157000145.0', 'Asuncor Negócios Imobiliários Ltda.', 'ASUNCOR NEGÓCIOS IMOBILIÁRIOS LTDA.', '9');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Asuncor Negócios Imobiliários Ltda.', '11.401.157/0001-45', '11401157000145.0', 'Asuncor Negócios Imobiliários Ltda.', 'ASUNCOR NEGÓCIOS IMOBILIÁRIOS LTDA.', '10');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Br Plásticos Indústria Ltda.', '05.491.005/0001-88', '5491005000188', 'BRP Compostos Ltda.', 'BR PLÁSTICOS INDÚSTRIA LTDA.', '11');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Br Plásticos Indústria Ltda.', '17.124.043/0001-81', '17124043000181.0', 'BRP Log Ltda.', 'BR PLÁSTICOS INDÚSTRIA LTDA.', '12');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Paludo Participações S.A.', '09.526.594/0001-43', '9526594000143.0', 'Banco Vipal S.A.', 'PALUDO PARTICIPAÇÕES S.A.', '13');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Borrachas Vipal Nordeste S.A.', '07.857.217/0001-61', '7857217000161.0', 'Borrachas Vipal Nordeste S.A.', 'BORRACHAS VIPAL NORDESTE S.A.', '14');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Borrachas Vipal Nordeste S.A.', '07.857.217/0002-42', '7857217000242.0', 'Borrachas Vipal Nordeste S.A.', 'BORRACHAS VIPAL NORDESTE S.A.', '15');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Borrachas Vipal S.A.', '87.870.952/0037-55', '87870952003755.0', 'Borrachas Vipal S.A.', 'BORRACHAS VIPAL S.A.', '16');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Borrachas Vipal S.A.', '87.870.952/0014-69', '87870952001469.0', 'Borrachas Vipal S.A.', 'BORRACHAS VIPAL S.A.', '17');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Borrachas Vipal S.A.', '87.870.952/0001-44', '87870952000144.0', 'Borrachas Vipal S.A.', 'BORRACHAS VIPAL S.A.', '18');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Borrachas Vipal S.A.', '87.870.952/0028-64', '87870952002864.0', 'Borrachas Vipal S.A.', 'BORRACHAS VIPAL S.A.', '19');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Borrachas Vipal S.A.', '87.870.952/0008-10', '87870952000810.0', 'Borrachas Vipal S.A.', 'BORRACHAS VIPAL S.A.', '20');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Borrachas Vipal S.A.', '87.870.952/0016-20', '87870952001620.0', 'Borrachas Vipal S.A.', 'BORRACHAS VIPAL S.A.', '21');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Borrachas Vipal S.A.', '87.870.952/0006-59', '87870952000659.0', 'Borrachas Vipal S.A.', 'BORRACHAS VIPAL S.A.', '22');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Borrachas Vipal S.A.', '87.870.952/0029-45', '87870952002945.0', 'Borrachas Vipal S.A.', 'BORRACHAS VIPAL S.A.', '23');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Borrachas Vipal S.A.', '87.870.952/0022-79', '87870952002279.0', 'Borrachas Vipal S.A.', 'BORRACHAS VIPAL S.A.', '24');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Borrachas Vipal S.A.', '87.870.952/0011-16', '87870952001116.0', 'Borrachas Vipal S.A.', 'BORRACHAS VIPAL S.A.', '25');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Borrachas Vipal S.A.', '87.870.952/0013-88', '87870952001388.0', 'Borrachas Vipal S.A.', 'BORRACHAS VIPAL S.A.', '26');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Borrachas Vipal S.A.', '87.870.952/0033-21', '87870952003321.0', 'Borrachas Vipal S.A.', 'BORRACHAS VIPAL S.A.', '27');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Borrachas Vipal S.A.', '87.870.952/0015-40', '87870952001540.0', 'Borrachas Vipal S.A.', 'BORRACHAS VIPAL S.A.', '28');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Borrachas Vipal S.A.', '87.870.952/0017-01', '87870952001701.0', 'Borrachas Vipal S.A.', 'BORRACHAS VIPAL S.A.', '29');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Borrachas Vipal S.A.', '87.870.952/0032-40', '87870952003240.0', 'Borrachas Vipal S.A.', 'BORRACHAS VIPAL S.A.', '30');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Borrachas Vipal S.A.', '87.870.952/0023-50', '87870952002350.0', 'Borrachas Vipal S.A.', 'BORRACHAS VIPAL S.A.', '31');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Borrachas Vipal S.A.', '87.870.952/0002-25', '87870952000225.0', 'Borrachas Vipal S.A.', 'BORRACHAS VIPAL S.A.', '32');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Borrachas Vipal S.A.', '87.870.952/0024-30', '87870952002430.0', 'Borrachas Vipal S.A.', 'BORRACHAS VIPAL S.A.', '33');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Borrachas Vipal S.A.', '87.870.952/0025-11', '87870952002511.0', 'Borrachas Vipal S.A.', 'BORRACHAS VIPAL S.A.', '34');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Borrachas Vipal S.A.', '87.870.952/0026-00', '87870952002600.0', 'Borrachas Vipal S.A.', 'BORRACHAS VIPAL S.A.', '35');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Borrachas Vipal S.A.', '87.870.952/0027-83', '87870952002783.0', 'Borrachas Vipal S.A.', 'BORRACHAS VIPAL S.A.', '36');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Borrachas Vipal S.A.', '87.870.952/0030-89', '87870952003089.0', 'Borrachas Vipal S.A.', 'BORRACHAS VIPAL S.A.', '37');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Borrachas Vipal S.A.', '87.870.952/0031-60', '87870952003160.0', 'Borrachas Vipal S.A.', 'BORRACHAS VIPAL S.A.', '38');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Borrachas Vipal S.A.', '87.870.952/0035-93', '87870952003593.0', 'Borrachas Vipal S.A.', 'BORRACHAS VIPAL S.A.', '39');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Borrachas Vipal S.A.', '87.870.952/0034-02', '87870952003402.0', 'Borrachas Vipal S.A.', 'BORRACHAS VIPAL S.A.', '40');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Borrachas Vipal S.A.', '87.870.952/0004-97', '87870952000497.0', 'Borrachas Vipal S.A.', 'BORRACHAS VIPAL S.A.', '41');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Br Plásticos Indústria Ltda.', '87.963.815/0001-54', '87963815000154.0', 'Br Plásticos Indústria Ltda.', 'BR PLÁSTICOS INDÚSTRIA LTDA.', '42');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Caravagio Empreendimentos e Incorporações Ltda.', '07.405.213/0001-42', '7405213000142.0', 'Caravagio Empreendimentos e Incorporações Ltda.', 'CARAVAGIO EMPREENDIMENTOS E INCORPORAÇÕES LTDA.', '43');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Cauchos Vipal, S.A. de C.V', 'None', 'None', 'Cauchos Vipal, S.A. de C.V', 'CAUCHOS VIPAL, S.A. DE C.V', '44');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Br Plásticos Indústria Ltda.', '09.305.097/0001-15', '9305097000115.0', 'Conforme Indústria Plástica Ltda.', 'BR PLÁSTICOS INDÚSTRIA LTDA.', '45');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Br Plásticos Indústria Ltda.', '09.305.097/0002-04', '9305097000204.0', 'Conforme Indústria Plástica Ltda.', 'BR PLÁSTICOS INDÚSTRIA LTDA.', '46');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Cya Rubber Distribuidora Ltda.', '04.435.399/0001-94', '4435399000194.0', 'Cya Rubber Distribuidora Ltda.', 'CYA RUBBER DISTRIBUIDORA LTDA.', '47');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Cya Rubber Distribuidora Ltda.', '04.435.399/0003-56', '4435399000356.0', 'Cya Rubber Distribuidora Ltda.', 'CYA RUBBER DISTRIBUIDORA LTDA.', '48');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Cya Rubber Distribuidora Ltda.', '04.435.399/0005-18', '4435399000518.0', 'Cya Rubber Distribuidora Ltda.', 'CYA RUBBER DISTRIBUIDORA LTDA.', '49');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Cya Rubber Distribuidora Ltda.', '04.435.399/0006-07', '4435399000607.0', 'Cya Rubber Distribuidora Ltda.', 'CYA RUBBER DISTRIBUIDORA LTDA.', '50');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Datami - Desenvolvimento Imobiliário Ltda.', '12.298.241/0001-48', '12298241000148.0', 'Datami - Desenvolvimento Imobiliário Ltda.', 'DATAMI - DESENVOLVIMENTO IMOBILIÁRIO LTDA.', '51');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Emppal Holding de Participações Ltda.', '12.697.021/0001-97', '12697021000197.0', 'Emppal Holding de Participações Ltda.', 'EMPPAL HOLDING DE PARTICIPAÇÕES LTDA.', '52');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Erval do Prata Indústria e ComÉrcio de Erva Mate Ltda.', '90.998.568/0001-36', '90998568000136.0', 'Erval do Prata Indústria e Comércio de Erva Mate Ltda.', 'ERVAL DO PRATA INDÚSTRIA E COMÉRCIO DE ERVA MATE LTDA.', '53');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', '12.357.041/0001-19', '12357041000119.0', 'Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', 'FATE PNEUS DO BRASIL S.A. - INDÚSTRIA, COMÉRCIO, IMPORTAÇÃO E EXPORTAÇÃO', '54');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', '12.357.041/0001-19', '12357041000119.0', 'Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', 'FATE PNEUS DO BRASIL S.A. - INDÚSTRIA, COMÉRCIO, IMPORTAÇÃO E EXPORTAÇÃO', '55');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', '12.357.041/0001-19', '12357041000119.0', 'Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', 'FATE PNEUS DO BRASIL S.A. - INDÚSTRIA, COMÉRCIO, IMPORTAÇÃO E EXPORTAÇÃO', '56');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', '12.357.041/0001-19', '12357041000119.0', 'Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', 'FATE PNEUS DO BRASIL S.A. - INDÚSTRIA, COMÉRCIO, IMPORTAÇÃO E EXPORTAÇÃO', '57');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', '12.357.041/0001-19', '12357041000119.0', 'Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', 'FATE PNEUS DO BRASIL S.A. - INDÚSTRIA, COMÉRCIO, IMPORTAÇÃO E EXPORTAÇÃO', '58');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', '12.357.041/0004-61', '12357041000461.0', 'Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', 'FATE PNEUS DO BRASIL S.A. - INDÚSTRIA, COMÉRCIO, IMPORTAÇÃO E EXPORTAÇÃO', '59');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', '12.357.041/0004-61', '12357041000461.0', 'Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', 'FATE PNEUS DO BRASIL S.A. - INDÚSTRIA, COMÉRCIO, IMPORTAÇÃO E EXPORTAÇÃO', '60');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', '12.357.041/0004-61', '12357041000461.0', 'Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', 'FATE PNEUS DO BRASIL S.A. - INDÚSTRIA, COMÉRCIO, IMPORTAÇÃO E EXPORTAÇÃO', '61');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', '12.357.041/0004-61', '12357041000461.0', 'Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', 'FATE PNEUS DO BRASIL S.A. - INDÚSTRIA, COMÉRCIO, IMPORTAÇÃO E EXPORTAÇÃO', '62');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', '12.357.041/0004-61', '12357041000461.0', 'Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', 'FATE PNEUS DO BRASIL S.A. - INDÚSTRIA, COMÉRCIO, IMPORTAÇÃO E EXPORTAÇÃO', '63');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', '12.357.041/0003-80', '12357041000380.0', 'Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', 'FATE PNEUS DO BRASIL S.A. - INDÚSTRIA, COMÉRCIO, IMPORTAÇÃO E EXPORTAÇÃO', '64');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', '12.357.041/0003-80', '12357041000380.0', 'Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', 'FATE PNEUS DO BRASIL S.A. - INDÚSTRIA, COMÉRCIO, IMPORTAÇÃO E EXPORTAÇÃO', '65');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', '12.357.041/0003-80', '12357041000380.0', 'Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', 'FATE PNEUS DO BRASIL S.A. - INDÚSTRIA, COMÉRCIO, IMPORTAÇÃO E EXPORTAÇÃO', '66');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', '12.357.041/0003-80', '12357041000380.0', 'Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', 'FATE PNEUS DO BRASIL S.A. - INDÚSTRIA, COMÉRCIO, IMPORTAÇÃO E EXPORTAÇÃO', '67');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', '12.357.041/0003-80', '12357041000380.0', 'Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', 'FATE PNEUS DO BRASIL S.A. - INDÚSTRIA, COMÉRCIO, IMPORTAÇÃO E EXPORTAÇÃO', '68');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', '12.357.041/0002-08', '12357041000208.0', 'Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', 'FATE PNEUS DO BRASIL S.A. - INDÚSTRIA, COMÉRCIO, IMPORTAÇÃO E EXPORTAÇÃO', '69');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', '12.357.041/0002-08', '12357041000208.0', 'Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', 'FATE PNEUS DO BRASIL S.A. - INDÚSTRIA, COMÉRCIO, IMPORTAÇÃO E EXPORTAÇÃO', '70');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', '12.357.041/0002-08', '12357041000208.0', 'Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', 'FATE PNEUS DO BRASIL S.A. - INDÚSTRIA, COMÉRCIO, IMPORTAÇÃO E EXPORTAÇÃO', '71');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', '12.357.041/0002-08', '12357041000208.0', 'Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', 'FATE PNEUS DO BRASIL S.A. - INDÚSTRIA, COMÉRCIO, IMPORTAÇÃO E EXPORTAÇÃO', '72');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', '12.357.041/0002-08', '12357041000208.0', 'Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', 'FATE PNEUS DO BRASIL S.A. - INDÚSTRIA, COMÉRCIO, IMPORTAÇÃO E EXPORTAÇÃO', '73');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', '12.357.041/0005-42', '12357041000542.0', 'Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', 'FATE PNEUS DO BRASIL S.A. - INDÚSTRIA, COMÉRCIO, IMPORTAÇÃO E EXPORTAÇÃO', '74');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', '12.357.041/0005-42', '12357041000542.0', 'Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', 'FATE PNEUS DO BRASIL S.A. - INDÚSTRIA, COMÉRCIO, IMPORTAÇÃO E EXPORTAÇÃO', '75');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', '12.357.041/0005-42', '12357041000542.0', 'Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', 'FATE PNEUS DO BRASIL S.A. - INDÚSTRIA, COMÉRCIO, IMPORTAÇÃO E EXPORTAÇÃO', '76');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', '12.357.041/0005-42', '12357041000542.0', 'Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', 'FATE PNEUS DO BRASIL S.A. - INDÚSTRIA, COMÉRCIO, IMPORTAÇÃO E EXPORTAÇÃO', '77');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', '12.357.041/0005-42', '12357041000542.0', 'Fate Pneus do Brasil S.A. - Indústria, Comércio, Importação e Exportação', 'FATE PNEUS DO BRASIL S.A. - INDÚSTRIA, COMÉRCIO, IMPORTAÇÃO E EXPORTAÇÃO', '78');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Idir Paludo', '134.408.880-53', '13440888053.0', 'Idir Paludo', 'IDIR PALUDO', '79');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Idirpar Participações S.A.', '09.157.401/0001-24', '9157401000124.0', 'Idirpar Participações S.A.', 'IDIRPAR PARTICIPAÇÕES S.A.', '80');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Inpal Participações Ltda.', '12.696.976/0001-20', '12696976000120.0', 'Inpal Participações Ltda.', 'INPAL PARTICIPAÇÕES LTDA.', '81');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Jpar Empreendimentos Ltda. - EPP', 'None', 'None', 'Jpar Empreendimentos Ltda. - EPP', 'JPAR EMPREENDIMENTOS LTDA. - EPP', '82');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Marpal Administração e Participações Ltda.', '05.962.751/0001-02', '5962751000102.0', 'Marpal Administração e Participações Ltda.', 'MARPAL ADMINISTRAÇÃO E PARTICIPAÇÕES LTDA.', '83');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Br Plásticos Indústria Ltda.', '12.637.710/0001-06', '12637710000106.0', 'Neoforma Soluções Construtivas Ltda.', 'BR PLÁSTICOS INDÚSTRIA LTDA.', '84');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Paludo Participações S.A.', '02.519.469/0001-67', '2519469000167.0', 'Paludo Agropecuária Ltda.', 'PALUDO PARTICIPAÇÕES S.A.', '85');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Paludo Participações S.A.', '93.169.340/0001-21', '93169340000121.0', 'Paludo Participações S.A.', 'PALUDO PARTICIPAÇÕES S.A.', '86');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Parpal Participações Ltda.', '12.697.030/0001-88', '12697030000188.0', 'Parpal Participações Ltda.', 'PARPAL PARTICIPAÇÕES LTDA.', '87');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Precon Indústria Plástica Ltda.', '02.246.955/0001-59', '2246955000159.0', 'Precon Indústria Plástica Ltda.', 'PRECON INDÚSTRIA PLÁSTICA LTDA.', '88');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Precon Indústria Plástica Ltda.', '02.246.955/0002-30', '2246955000230.0', 'Precon Indústria Plástica Ltda.', 'PRECON INDÚSTRIA PLÁSTICA LTDA.', '89');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Precon Indústria Plástica Ltda.', '02.246.955/0003-10', '2246955000310.0', 'Precon Indústria Plástica Ltda.', 'PRECON INDÚSTRIA PLÁSTICA LTDA.', '90');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Renan Batista Patrício Lima', '473.481.350-72', '47348135072.0', 'Renan Batista Patrício Lima', 'RENAN BATISTA PATRÍCIO LIMA', '91');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Ridi Participações Ltda.', '09.451.149/0001-61', '9451149000161.0', 'Ridi Participações Ltda.', 'RIDI PARTICIPAÇÕES LTDA.', '92');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Paludo Participações S.A.', '05.950.679/0001-01', '5950679000101.0', 'Risorse Fomento Mercantil Ltda.', 'PALUDO PARTICIPAÇÕES S.A.', '93');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Paludo Participações S.A.', '05.950.679/0003-65', '5950679000365.0', 'Risorse Fomento Mercantil Ltda.', 'PALUDO PARTICIPAÇÕES S.A.', '94');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Sifra Pneumáticos Ltda.', '06.003.652/0001-66', '6003652000166.0', 'Sifra Pneumáticos Ltda.', 'SIFRA PNEUMÁTICOS LTDA.', '95');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Silver Participações Ltda.', '09.286.565/0001-51', '9286565000151.0', 'Silver Participações Ltda.', 'SILVER PARTICIPAÇÕES LTDA.', '96');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Taiana Paludo', '721.530.910-04', '72153091004.0', 'Taiana Paludo', 'TAIANA PALUDO', '97');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Titopar Participações Ltda.', '09.025.269/0001-05', '9025269000105.0', 'Titopar Participações Ltda.', 'TITOPAR PARTICIPAÇÕES LTDA.', '98');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Br Plásticos Indústria Ltda.', '81.522.690/0001-40', '81522690000140.0', 'Tubozan Indústria Plástica Ltda.', 'BR PLÁSTICOS INDÚSTRIA LTDA.', '99');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Br Plásticos Indústria Ltda.', '81.522.690/0003-02', '81522690000302.0', 'Tubozan Indústria Plástica Ltda.', 'BR PLÁSTICOS INDÚSTRIA LTDA.', '100');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Br Plásticos Indústria Ltda.', '81.522.690/0002-21', '81522690000221.0', 'Tubozan Indústria Plástica Ltda.', 'BR PLÁSTICOS INDÚSTRIA LTDA.', '101');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('VAP Participações S.A.', '93.196.020/0001-60', '93196020000160.0', 'VAP Participações S.A.', 'VAP PARTICIPAÇÕES S.A.', '102');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Vicêncio Paludo', '026.462.260-04', '2646226004.0', 'Vicêncio Paludo', 'VICÊNCIO PALUDO', '103');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Vicêncio Paludo, Filhos & Cia Ltda.', '91.615.039/0001-79', '91615039000179.0', 'Vicêncio Paludo, Filhos & Cia Ltda.', 'VICÊNCIO PALUDO, FILHOS & CIA LTDA.', '104');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Vipal Indústria de Máquinas Ltda.', '05.957.233/0001-09', '5957233000109.0', 'Vipal Indústria de Máquinas Ltda.', 'VIPAL INDÚSTRIA DE MÁQUINAS LTDA.', '105');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Vipal Indústria de Máquinas Ltda.', '05.957.233/0002-81', '5957233000281.0', 'Vipal Indústria de Máquinas Ltda.', 'VIPAL INDÚSTRIA DE MÁQUINAS LTDA.', '106');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Vipal Participadas España S.L.', 'None', 'None', 'Vipal Participadas España S.L.', 'VIPAL PARTICIPADAS ESPAÑA S.L.', '107');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Vipal S.A.', 'None', 'None', 'Vipal S.A.', 'VIPAL S.A.', '108');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Vipaltec - Pesquisa e Desenvolvimento Tecnológico Ltda.', '08.295.540/0001-51', '8295540000151.0', 'Vipaltec - Pesquisa e Desenvolvimento Tecnológico Ltda.', 'VIPALTEC - PESQUISA E DESENVOLVIMENTO TECNOLÓGICO LTDA.', '109');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Paludo Participações S.A.', '08.779.422/0001-19', '8779422000119.0', 'Vipar Participações Ltda.', 'PALUDO PARTICIPAÇÕES S.A.', '110');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Vitapar Participações Ltda.', '06.964.289/0001-45', '6964289000145.0', 'Vitapar Participações Ltda.', 'VITAPAR PARTICIPAÇÕES LTDA.', '111');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Marangoni Tread Latino América S.A. Indústria e Comércio de Artefatos de Borracha', '02.551.474/0001-57', '2551474000157.0', 'Marangoni Tread Latino América S.A. Indústria e Comércio de Artefatos de Borracha', 'MARANGONI TREAD LATINO AMÉRICA S.A. INDÚSTRIA E COMÉRCIO DE ARTEFATOS DE BORRACHA', '112');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Marangoni Tread Latino América S.A. Indústria e Comércio de Artefatos de Borracha', '67.479.931/0001-95', '67479931000195.0', 'RT Rio Preto Reformas de Pneus Ltda.', 'MARANGONI TREAD LATINO AMÉRICA S.A. INDÚSTRIA E COMÉRCIO DE ARTEFATOS DE BORRACHA', '113');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Marangoni Tread Latino América S.A. Indústria e Comércio de Artefatos de Borracha', '06.211.192/0001-61', '6211192000161.0', 'RT Canoas Reformas de Pneus Ltda.', 'MARANGONI TREAD LATINO AMÉRICA S.A. INDÚSTRIA E COMÉRCIO DE ARTEFATOS DE BORRACHA', '114');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Marangoni Tread Latino América S.A. Indústria e Comércio de Artefatos de Borracha', '09.523.553/0001-01', '9523553000101.0', 'JF Recap Reformadora de Pneus Ltda.', 'MARANGONI TREAD LATINO AMÉRICA S.A. INDÚSTRIA E COMÉRCIO DE ARTEFATOS DE BORRACHA', '115');
INSERT INTO db_clientes ("#Clientes", "CPF_CNPJ", "CPF_CNPJ_Conv", "Clientes", "Clientes_Maiusc", "Índice") VALUES ('Marangoni Tread Latino América S.A. Indústria e Comércio de Artefatos de Borracha', 'None', 'None', 'RT Bicas Reforma de Pneus Ltda.', 'MARANGONI TREAD LATINO AMÉRICA S.A. INDÚSTRIA E COMÉRCIO DE ARTEFATOS DE BORRACHA', '116');

CREATE TABLE IF NOT EXISTS db_polo (
  "Polo" TEXT,
  "Risco" TEXT,
  "Índice" TEXT
);

INSERT INTO db_polo ("Polo", "Risco", "Índice") VALUES ('Ativo', 'Ganho Possível', '1');
INSERT INTO db_polo ("Polo", "Risco", "Índice") VALUES ('Ativo', 'Ganho Provável', '2');
INSERT INTO db_polo ("Polo", "Risco", "Índice") VALUES ('Ativo', 'Ganho Remoto', '3');
INSERT INTO db_polo ("Polo", "Risco", "Índice") VALUES ('Passivo', 'Perda Possível', '4');
INSERT INTO db_polo ("Polo", "Risco", "Índice") VALUES ('Passivo', 'Perda Provável', '5');
INSERT INTO db_polo ("Polo", "Risco", "Índice") VALUES ('Passivo', 'Perda Remota', '6');

CREATE TABLE IF NOT EXISTS db_risco (
  "#Risco" TEXT,
  "Risco" TEXT,
  "Índice" TEXT
);

INSERT INTO db_risco ("#Risco", "Risco", "Índice") VALUES ('B - Possível', 'Ganho Possível', '1');
INSERT INTO db_risco ("#Risco", "Risco", "Índice") VALUES ('A - Provável', 'Ganho Provável', '2');
INSERT INTO db_risco ("#Risco", "Risco", "Índice") VALUES ('C - Remota', 'Ganho Remoto', '3');
INSERT INTO db_risco ("#Risco", "Risco", "Índice") VALUES ('B - Possível', 'Perda Possível', '4');
INSERT INTO db_risco ("#Risco", "Risco", "Índice") VALUES ('A - Provável', 'Perda Provável', '5');
INSERT INTO db_risco ("#Risco", "Risco", "Índice") VALUES ('C - Remota', 'Perda Remota', '6');

